apiVersion: v1
entries:
  orbit:
  - apiVersion: v1
    appVersion: 2.0.0-alpha.46
    created: "2020-03-16T21:57:39.7158024Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 32b849d064af5325f936208995940c78172e854f657b6121562aee16a0dafc05
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.46/orbit-2.0.0-alpha.46.tgz
    version: 2.0.0-alpha.46
  - apiVersion: v1
    appVersion: 2.0.0-alpha.45
    created: "2020-03-16T21:48:54.945239749Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 226a61f1d357b97c5085fe7645b41372ed8b3f079d2d49bcfd020ef4cf84bb5f
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.45/orbit-2.0.0-alpha.45.tgz
    version: 2.0.0-alpha.45
  - apiVersion: v1
    appVersion: 2.0.0-alpha.44
    created: "2020-03-16T21:39:56.449268119Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: acb838211294ddfddd174ee977dbf07bd9af2bd1aabb9517ad645d4ed91b3768
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.44/orbit-2.0.0-alpha.44.tgz
    version: 2.0.0-alpha.44
  - apiVersion: v1
    appVersion: 2.0.0-alpha.43
    created: "2020-03-16T21:28:48.405914016Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: f395f4cb9f13b1fd55e88be373ed13aa22d3e167d807e03beeaafef5310f07fb
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.43/orbit-2.0.0-alpha.43.tgz
    version: 2.0.0-alpha.43
  - apiVersion: v1
    appVersion: 2.0.0-alpha.42
    created: "2020-03-16T21:18:43.789243463Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 3a5fd951647d1583bc83e92ec962fd6be366ac99c9ef550a5a58e168b3ac4b45
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.42/orbit-2.0.0-alpha.42.tgz
    version: 2.0.0-alpha.42
  - apiVersion: v1
    appVersion: 2.0.0-alpha.39
    created: "2020-03-12T00:22:53.861783136Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 61417e593ea1807ae18a40038e51dd791256aa6ff2b51a2cbd9783c5250142e8
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.39/orbit-2.0.0-alpha.39.tgz
    version: 2.0.0-alpha.39
  - apiVersion: v1
    appVersion: 2.0.0-alpha.36
    created: "2020-02-13T00:26:39.760344906Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 39033d3dd3c71cf838577588ada5b2f599deec88415ed4e50b89a38a030f2925
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.36/orbit-2.0.0-alpha.36.tgz
    version: 2.0.0-alpha.36
  - apiVersion: v1
    appVersion: 2.0.0-alpha.35
    created: "2020-02-12T21:44:20.351361621Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 84d88f26ee96a704a94861f7d3d4b11e59ec8880eb12d4af8ecc47c618c7280b
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.35/orbit-2.0.0-alpha.35.tgz
    version: 2.0.0-alpha.35
  - apiVersion: v1
    appVersion: 2.0.0-alpha.34
    created: "2020-02-07T20:09:57.93745297Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 1750e70a059b32409dc2a48a89b624fa420d12accb0327650795412ee5ee9bda
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.34/orbit-2.0.0-alpha.34.tgz
    version: 2.0.0-alpha.34
  - apiVersion: v1
    appVersion: 2.0.0-alpha.33
    created: "2020-02-07T18:39:04.371079017Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 6cf6e5316fae53dc2a40e4040a74a855bcc48b946565fb8ca3d20100b35e22bf
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.33/orbit-2.0.0-alpha.33.tgz
    version: 2.0.0-alpha.33
  - apiVersion: v1
    appVersion: 2.0.0-alpha.32
    created: "2020-01-31T15:42:30.515968282Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 120d0aa2a7ece3a11d4b1f044c422d678cadd64dea031c4aba26789d67fe7fa7
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.32/orbit-2.0.0-alpha.32.tgz
    version: 2.0.0-alpha.32
  - apiVersion: v1
    appVersion: 2.0.0-alpha.30
    created: "2020-01-30T20:10:26.874032531Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 13c964c023ce9400170ccf3eeb03b67f5e7b1b57027fa61f8d838ae1c7377b72
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.30/orbit-2.0.0-alpha.30.tgz
    version: 2.0.0-alpha.30
  - apiVersion: v1
    appVersion: 2.0.0-alpha.29
    created: "2020-01-28T00:40:55.459719529Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 6294b7d312bc558f026b4df17b7dcbb6c2bea1f7003472975d3c2e6a4d4f827a
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.29/orbit-2.0.0-alpha.29.tgz
    version: 2.0.0-alpha.29
  - apiVersion: v1
    appVersion: 2.0.0-alpha.27
    created: "2020-01-23T00:15:20.79142234Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 5e9cbe64833dc0556a7fab696662cff6e699facee74c0e8d5aa28560da07e92c
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.27/orbit-2.0.0-alpha.27.tgz
    version: 2.0.0-alpha.27
  - apiVersion: v1
    appVersion: 2.0.0-alpha.26
    created: "2020-01-22T01:08:36.800591485Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 2ce5c3d59f7b8c99c576aa547a7a80409d793596198e0798e213241465ff9e2d
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.26/orbit-2.0.0-alpha.26.tgz
    version: 2.0.0-alpha.26
  - apiVersion: v1
    appVersion: 2.0.0-alpha.25
    created: "2020-01-17T18:25:14.249718939Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: f9ebaab36f817d257958483bb75819c94c7c23a2257c2d40453e39591ea3a06c
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.25/orbit-2.0.0-alpha.25.tgz
    version: 2.0.0-alpha.25
  - apiVersion: v1
    appVersion: 2.0.0-alpha.24.4
    created: "2020-01-17T17:58:39.106237456Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 1f41ea501a475ae0223c1de2a035e291e9c39b5c055ecee3fe9b92c169b3cca4
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.24.4/orbit-2.0.0-alpha.24.4.tgz
    version: 2.0.0-alpha.24.4
  - apiVersion: v1
    appVersion: 2.0.0-alpha.24.3
    created: "2020-01-17T01:48:10.181137297Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 49baab6646c356fa29ccbd4c3a6be57e4adc1108033652185a29f181937d6e93
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.24.3/orbit-2.0.0-alpha.24.3.tgz
    version: 2.0.0-alpha.24.3
  - apiVersion: v1
    appVersion: 2.0.0-alpha.24
    created: "2020-01-16T20:22:55.449918354Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: e405e28c0c6ca54be50c396839c05aace89bd7e01022e0f591e4facdbdbf9146
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.24/orbit-2.0.0-alpha.24.tgz
    version: 2.0.0-alpha.24
  - apiVersion: v1
    appVersion: 2.0.0-alpha.23.1
    created: "2020-01-16T20:03:16.600002798Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: b23b1a0ecf562429c337f117fc5a2765d01c8ccef7faa6bf9ecfc1cc508858bc
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.23.1/orbit-2.0.0-alpha.23.1.tgz
    version: 2.0.0-alpha.23.1
generated: "2020-03-16T21:57:39.714825006Z"
