apiVersion: v1
entries:
  orbit:
  - apiVersion: v1
    appVersion: 2.0.0-alpha.26
    created: "2020-01-22T01:08:36.800591485Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 2ce5c3d59f7b8c99c576aa547a7a80409d793596198e0798e213241465ff9e2d
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.26/orbit-2.0.0-alpha.26.tgz
    version: 2.0.0-alpha.26
  - apiVersion: v1
    appVersion: 2.0.0-alpha.25
    created: "2020-01-17T18:25:14.249718939Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: f9ebaab36f817d257958483bb75819c94c7c23a2257c2d40453e39591ea3a06c
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.25/orbit-2.0.0-alpha.25.tgz
    version: 2.0.0-alpha.25
  - apiVersion: v1
    appVersion: 2.0.0-alpha.24.4
    created: "2020-01-17T17:58:39.106237456Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 1f41ea501a475ae0223c1de2a035e291e9c39b5c055ecee3fe9b92c169b3cca4
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.24.4/orbit-2.0.0-alpha.24.4.tgz
    version: 2.0.0-alpha.24.4
  - apiVersion: v1
    appVersion: 2.0.0-alpha.24.3
    created: "2020-01-17T01:48:10.181137297Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 49baab6646c356fa29ccbd4c3a6be57e4adc1108033652185a29f181937d6e93
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.24.3/orbit-2.0.0-alpha.24.3.tgz
    version: 2.0.0-alpha.24.3
  - apiVersion: v1
    appVersion: 2.0.0-alpha.24
    created: "2020-01-16T20:22:55.449918354Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: e405e28c0c6ca54be50c396839c05aace89bd7e01022e0f591e4facdbdbf9146
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.24/orbit-2.0.0-alpha.24.tgz
    version: 2.0.0-alpha.24
  - apiVersion: v1
    appVersion: 2.0.0-alpha.23.1
    created: "2020-01-16T20:03:16.600002798Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: b23b1a0ecf562429c337f117fc5a2765d01c8ccef7faa6bf9ecfc1cc508858bc
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.23.1/orbit-2.0.0-alpha.23.1.tgz
    version: 2.0.0-alpha.23.1
generated: "2020-01-22T01:08:36.800066284Z"
