apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "orbit.fullname" . }}-addressable-directory
  labels:
    app: {{ include "orbit.name" . }}
    chart: {{ include "orbit.chart" . }}
    release: {{ .Release.Name }}
    component: addressable-directory
    tier: "persistence"
spec:
  replicas: {{ .Values.addressableDirectory.replicas }}
  selector:
    matchLabels:
      app: {{ include "orbit.name" . }}
      release: {{ .Release.Name }}
      component: addressable-directory
  template:
    metadata:
      labels:
        app: {{ include "orbit.name" . }}
        release: {{ .Release.Name }}
        component: addressable-directory
        tier: "persistence"
    spec:
    {{- with .Values.addressableDirectory }}
      containers:
      - name: addressable-directory
        image: {{ .image.repository }}
        ports:
        - containerPort: {{ .clientPort }}
        - containerPort: {{ .peerPort }}
        env:
        - name: ALLOW_NONE_AUTHENTICATION
          value: "yes"
        - name: ETCD_ADVERTISE_CLIENT_URLS
          value: "http://addressable-directory:{{ .clientPort }}"
    {{- end }}
