apiVersion: v1
kind: Service
metadata:
  name: {{ include "orbit.fullname" . }}-addressable-directory
  labels:
    app: {{ include "orbit.name" . }}
    chart: {{ include "orbit.chart" . }}
    release: {{ .Release.Name }}
    component: addressable-directory
spec:
  selector:
    app: {{ include "orbit.name" . }}
    release: {{ .Release.Name }}
    component: addressable-directory
    tier: "persistence"
  ports:
  - name: client
    port: {{ .Values.addressableDirectory.clientPort }}
  - name: peer
    port: {{ .Values.addressableDirectory.peerPort }}
