apiVersion: v1
kind: Service
metadata:
  name: {{ include "orbit.fullname" . }}-node-directory
  labels:
    app: {{ include "orbit.name" . }}
    chart: {{ include "orbit.chart" . }}
    release: {{ .Release.Name }}
    component: node-directory
spec:
  selector:
    app: {{ include "orbit.name" . }}
    release: {{ .Release.Name }}
    component: node-directory
  ports:
  - name: client
    port: {{ .Values.nodeDirectory.clientPort }}
  - name: peer
    port: {{ .Values.nodeDirectory.peerPort }}
