version: "3.7"
services:
  orbit-server-1:
    build:
      context: ../
      dockerfile: docker/server/Dockerfile
    ports:
      - "5006:5005"
    expose:
      - 50056
    environment:
      ORBIT_URL: "orbit-server-1:50056"
      ORBIT_PORT: 50056
      NODE_DIRECTORY: http://node-directory:2379
      ADDRESSABLE_DIRECTORY: http://addressable-directory:2379
    entrypoint: sh ./opt/orbit/entrypoint.sh
    volumes:
      - ../src/orbit-application/build/libs/orbit-application-fat-2-SNAPSHOT.jar:/opt/orbit/libs/orbit-application-fat.jar
  orbit-server-2:
    build:
      context: ../
      dockerfile: docker/server/Dockerfile
    ports:
      - "5007:5005"
    expose:
      - 50056
    environment:
      ORBIT_URL: "orbit-server-2:50056"
      ORBIT_PORT: 50056
      NODE_DIRECTORY: http://node-directory:2379
      ADDRESSABLE_DIRECTORY: http://addressable-directory:2379
    entrypoint: sh -c ./opt/orbit/entrypoint.sh
    volumes:
      - ../src/orbit-application/build/libs/orbit-application-fat-2-SNAPSHOT.jar:/opt/orbit/libs/orbit-application-fat.jar
  node-directory:
    image: bitnami/etcd
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd-server:2379
    expose:
      - 2379
      - 2380
  addressable-directory:
    image: bitnami/etcd
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd-server:2379
    expose:
      - 2379
      - 2380
  test-webpage:
    build:
      context: ../
      dockerfile: docker/test-webpage/Dockerfile
    volumes:
      - ../src/orbit-test-webpage:/opt/orbit/web
      - /opt/orbit/web/node_modules
    ports:
      - 80:3000
    environment:
      REACT_APP_API_URLS: "http://localhost:8080,http://localhost:8081"
    entrypoint: npm start
  test-api-1:
    build:
      context: ../
      dockerfile: docker/test-api/Dockerfile
    volumes:
      - ../src/orbit-test-api:/opt/orbit/api
      - /opt/orbit/api/node_modules
      - ../src/orbit-proto/src/main/proto:/opt/orbit/api/proto
    ports:
      - 8080:3000
      - 9229:9229
    environment:
      ORBIT_URL: orbit-server-1:50056
    entrypoint: npm run dev
  test-api-2:
    build:
      context: ../
      dockerfile: docker/test-api/Dockerfile
    volumes:
      - ../src/orbit-test-api:/opt/orbit/api
      - /opt/orbit/api/node_modules
      - ../src/orbit-proto/src/main/proto:/opt/orbit/api/proto
    ports:
      - 8081:3000
      - 9230:9229
    environment:
      ORBIT_URL: orbit-server-2:50056
    entrypoint: npm run dev
  proxy:
    image: haproxy:2.0-alpine
    depends_on:
      - test-api-1
      - test-api-2
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - ./proxy/config:/usr/local/etc/haproxy:rw
    restart: always
