version: "3.7"
services:
  orbit-server-1:
    build:
      context: ../
      dockerfile: docker/server/Dockerfile
    ports:
      - "50056:50056"
    environment:
      ORBIT_HOST: "orbit-server-1"
      ORBIT_PORT: 50056
      ETCD_SERVER: http://node-directory:2379
    entrypoint: sh ./opt/orbit/entrypoint.sh
    volumes:
      - ../src/orbit-application/build/libs:/opt/orbit/libs
  orbit-server-2:
    build:
      context: ../
      dockerfile: docker/server/Dockerfile
    ports:
      - "50057:50057"
    environment:
      ORBIT_HOST: "orbit-server-2"
      ORBIT_PORT: 50057
      ETCD_SERVER: http://node-directory:2379
    entrypoint: sh -c ./opt/orbit/entrypoint.sh
    volumes:
      - ../src/orbit-application/build/libs:/opt/orbit/libs
  node-directory:
    image: bitnami/etcd
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd-server:2379
    ports:
      - "2379:2379"
      - "2380:2380"
    expose:
      - 2379
      - 2380

#      ETCD_ROOT_PASSWORD: pass
