version: "3.7"
services:
  orbit-server-1:
    build:
      context: ../
      dockerfile: docker/server/Dockerfile
    ports:
      - "5006:5005"
      - "50056:50056"
    expose:
      - 50056
    environment:
      ORBIT_URL: "orbit-server-1:50056"
      ORBIT_PORT: 50056
      NODE_DIRECTORY: http://node-directory:2379
      ADDRESSABLE_DIRECTORY: http://addressable-directory:2379
    entrypoint: sh ./opt/orbit/entrypoint.sh
    volumes:
      - ../src/orbit-application/build/libs:/opt/orbit/libs
  orbit-server-2:
    build:
      context: ../
      dockerfile: docker/server/Dockerfile
    ports:
      - "5007:5005"
      - "50057:50056"
    expose:
      - 50056
    environment:
      ORBIT_URL: "orbit-server-2:50056"
      ORBIT_PORT: 50056
      NODE_DIRECTORY: http://node-directory:2379
      ADDRESSABLE_DIRECTORY: http://addressable-directory:2379
    entrypoint: sh -c ./opt/orbit/entrypoint.sh
    volumes:
      - ../src/orbit-application/build/libs:/opt/orbit/libs
  node-directory:
    image: bitnami/etcd
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd-server:2379
    expose:
      - 2379
      - 2380
  addressable-directory:
    image: bitnami/etcd
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd-server:2379
    expose:
      - 2379
      - 2380
