version: "3.7"
services:
  orbit_server_1:
    build:
      context: ../
      dockerfile: docker/server/Dockerfile
    ports:
      - "50056:50056"
    entrypoint: sh ./opt/orbit/entrypoint.sh
    volumes:
      - ../src/orbit-application/build/libs:/opt/orbit/libs
  orbit_server_2:
    build:
      context: ../
      dockerfile: docker/server/Dockerfile
    ports:
      - "50057:50056"
    entrypoint: sh -c ./opt/orbit/entrypoint.sh
    volumes:
      - ../src/orbit-application/build/libs:/opt/orbit/libs
  node_directory:
    image: bitnami/etcd
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd-server:2379
    ports:
      - "2379:2379"
      - "2380:2380"

#      ETCD_ROOT_PASSWORD: pass
