name: Publish Helm Chart

on: [push, pull_request]

jobs:
  build:
    name: Build on JDK ${{ matrix.jdk }}
    strategy:
      matrix:
        jdk: [ '8', '11', '13' ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Publish Helm Chart
        uses: helm/chart-releaser-action@v1.0.0-alpha.2
        with:
          access-token: "${{ secrets.GITHUB_TOKEN }}"
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"